# $Id: Makefile 584389 2013-06-04 05:34:41Z ib-builder $
#
# Copyright (c) 2011-2013, Juniper Networks, Inc.
# All rights reserved.
#

UPDATE_DEPENDFILE = NO

all: build_uboot.ex62xx

build_uboot.ex62xx: _BUILD_UBOOT_USE

build_uboot.ex62xx: .META
XMAKE_META_FILE = build_uboot.ex62xx.meta

.include "../Makefile.inc"

